# 应用服务 WEB 访问端口
server:
  port: 8080


logging:
  level:
#    指定 tutor 包的日志级别，小于的不打印
    org.tutor: info

# profiles.active 指定其他项目或者自身项目下的 yml 配置
spring:
  profiles:
    active: private


mybatis:
  mapper-locations: classpath:mapper/*.xml