# 应用服务 WEB 访问端口
server:
  port: 8080


logging:
  level:
#    指定 tutor 包的日志级别，小于的不打印
    org.tutor: info

# profiles.active 指定其他项目或者自身项目下的 yml 配置
spring:
  profiles:
    active: private
  # Quartz 的配置，对应 QuartzProperties 配置类
  quartz:
    job-store-type: memory # Job 存储器类型。默认为 memory 表示内存，可选 jdbc 使用数据库。
    auto-startup: false # Quartz 是否自动启动
    startup-delay: 0 # 延迟 N 秒启动
    wait-for-jobs-to-complete-on-shutdown: true # 应用关闭时，是否等待定时任务执行完成。默认为 false ，建议设置为 true
    overwrite-existing-jobs: false # 是否覆盖已有 Job 的配置
    properties: # 添加 Quartz Scheduler 附加属性
      org:
        quartz:
          threadPool:
            threadCount: 25 # 线程池大小。默认为 10 。
            threadPriority: 5 # 线程优先级
            class: org.quartz.simpl.SimpleThreadPool # 线程池类型
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/Tutor_Ali?serverTimezone=UTC&characterEncoding=utf8
#    username: tutor
#    password: password
#  redis:
#    host: localhost
#    port: 6379
#    password: password


mybatis:
  mapper-locations: classpath:mapper/*.xml